#!/usr/bin/env python3

import argparse
import grpc
import sys

import fossildbapi_pb2 as proto
import fossildbapi_pb2_grpc as proto_rpc

from grpc_health.v1 import health_pb2
from grpc_health.v1 import health_pb2_grpc

def main():

    commands = {
        'backup': lambda stub:
            stub.Backup(proto.BackupRequest()),
        'restore': lambda stub:
            stub.RestoreFromBackup(proto.RestoreFromBackupRequest()),
        'health': None
    }

    parser = argparse.ArgumentParser()
    parser.add_argument(
        'address', metavar='address', default='localhost', nargs='?',
        help='address of the fossildb server (default: %(default)s)')
    parser.add_argument(
        'port', metavar='port', type=int, default=7155,  nargs='?',
        help='port of the fossildb server (default: %(default)s)')
    parser.add_argument(
        'command', metavar='command',
        help='command to execute, one of {}'.format(list(commands.keys())))

    args = parser.parse_args()

    if args.command not in commands:
        print("command {} is not available".format(args.command))
        parser.print_help()
        exit(20)

    full_address = '{}:{}'.format(args.address, args.port)

    print('Connecting to FossilDB at', full_address)

    channel = grpc.insecure_channel(full_address)
    stub = proto_rpc.FossilDBStub(channel)
    healthStub = health_pb2_grpc.HealthStub(channel)

    if args.command == 'health':
        try :
            reply = healthStub.Check(health_pb2.HealthCheckRequest(service=''))
            print(reply)
            UNKNOWN = 0;
            SERVING = 1;
            NOT_SERVING = 2;
            if reply.status != SERVING:
                raise Exception(reply.status)
        except Exception as e:
            print('Health check unsuccessful. FossilDB offline?')
            print(e)
            sys.exit(1)

    else:
        reply = commands[args.command](stub)
        print(reply)
        if not reply.success:
            sys.exit(1)


if __name__ == '__main__':
    main()
