version: '2.1'

services:
  fossildb:
    image: scalableminds/fossildb:${FOSSILDB_TAG:-master}
    entrypoint: fossildb
    command:
      - -c
      - default
    ports:
      - "7155:7155"
    volumes:
      - "./data:/fossildb/data"
      - "./backup:/fossildb/backup"

  fossildb-health-check:
    image: scalableminds/fossildb-client:${FOSSILDB_CLIENT_TAG:-master}
    command:
      - fossildb
      - health
    links:
      - fossildb

  client:
    image: scalableminds/fossildb-client:${FOSSILDB_CLIENT_TAG:-master}
    volumes:
      - ".:/app"
    working_dir: /app
    entrypoint: /bin/bash
    network_mode: host

  sbt:
    image: scalableminds/sbt:${SBT_VERSION_TAG:-master__7830403826}
    environment:
      - USER_UID
      - USER_GID
      - TZ
    working_dir: /fossildb
    user: ${USER_UID:-1000}:${USER_GID:-1000}
    volumes:
      - ".:/fossildb"
