version: '2.1'

services:
  fossildb:
    image: scalableminds/fossildb:${FOSSILDB_TAG:-master}
    entrypoint: fossildb
    command:
      - -c
      - skeletons
    ports:
      - "7155:7155"
    volumes:
      - "./data:/fossildb/data"
      - "./backup:/fossildb/backup"

  fossildb-health-check:
    image: scalableminds/fossildb-client:${FOSSILDB_CLIENT_TAG:-master}
    command:
      - fossildb
      - health
    links:
      - fossildb

  sbt:
    image: scalableminds/sbt:${SBT_VERSION_TAG:-sbt-0.13.15_mongo-3.2.17_node-8.x_jdk-8}
    environment:
      - USER_UID
      - USER_GID
      - TZ
    working_dir: /fossildb
    volumes:
      - ".:/fossildb"
      - "~/.m2:/home/sbt-user/.m2"
      - "~/.ivy2:/home/sbt-user/.ivy2"
      - "~/.sbt:/home/sbt-user/.sbt"
