#!/bin/bash
set -Eeuo pipefail

FOSSILDB_HOME=$(dirname $(readlink -f $0))

if [ "$(id -u)" = '0' ]; then
  for SUBDIR in data backup; do
    DIR=$FOSSILDB_HOME/$SUBDIR
    if [ -d "$DIR" ]; then
      chown -R fossildb  $DIR
    fi
  done
  exec gosu fossildb java -jar $FOSSILDB_HOME/fossildb.jar $@
else
  exec java -jar $FOSSILDB_HOME/fossildb.jar $@
fi
