#!/bin/bash
set -Eeuo pipefail

FOSSILDB_HOME=$(dirname $(readlink -f $0))

if [ "$(id -u)" = '0' ]; then
  chown -R fossildb $FOSSILDB_HOME/data $FOSSILDB_HOME/backup
  exec gosu fossildb java -jar $FOSSILDB_HOME/fossildb.jar $@
else
  exec java -jar $FOSSILDB_HOME/fossildb.jar $@
fi
