version: 2
get_common_build_num: &get_common_build_num
  name: Export commond build number
  command: echo "export COMMON_BUILD_NUM=$(cat /common/build)" >> $BASH_ENV
jobs:
  set_common_build_number:
    steps:
      - run:
          name: Write build number
          command: echo "${CIRCLE_BUILD_NUM}" > common/build
      - persist_to_workspace:
          root: common
          paths:
            - build
  build_and_push_db:
    machine:
      image: circleci/classic:latest
    environment:
      SBT_VERSION_TAG: sbt-0.13.15_mongo-3.2.17_node-8.x_jdk-8
      USER_UID: 1001
      USER_GID: 1001
    steps:
      - checkout
      - attach_workspace:
          at: /common
      - run: *get_common_build_num
      - run:
          name: Prepare dependency folders
          command: mkdir -p ~/.m2 ~/.ivy2 ~/.sbt
      - restore_cache:
          key: cache-{{ .Branch }}
      - run:
          name: Build server
          command: docker-compose run sbt sbt assembly
      - save_cache:
          key: cache-{{ .Branch }}
          paths:
            - "~/.m2"
            - "~/.ivy2"
            - "~/.sbt"
      - run:
          name: Build server docker image
          command: |
            docker build \
            -t scalableminds/fossildb:${CIRCLE_BRANCH}__${COMMON_BUILD_NUM} \
            -t scalableminds/fossildb:${CIRCLE_BRANCH} \
            .
      - run:
          name: Push to DockerHub
          command: |
            set -x
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push scalableminds/fossildb:${CIRCLE_BRANCH}__${COMMON_BUILD_NUM}
            docker push scalableminds/fossildb:${CIRCLE_BRANCH}
            docker logout
  build_and_push_client:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - attach_workspace:
          at: /common
      - run: *get_common_build_num
      - run:
          name: Build client docker image
          command: |
            docker build \
            -f client/Dockerfile \
            -t scalableminds/fossildb-client:${CIRCLE_BRANCH}__${COMMON_BUILD_NUM} \
            -t scalableminds/fossildb-client:${CIRCLE_BRANCH} \
            .
      - run:
          name: Push to DockerHub
          command: |
            set -x
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push scalableminds/fossildb-client:${CIRCLE_BRANCH}__${COMMON_BUILD_NUM}
            docker push scalableminds/fossildb-client:${CIRCLE_BRANCH}
            docker logout
  smoketest:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - attach_workspace:
          at: /common
      - run: *get_common_build_num
      - run:
          name: Pull from DockerHub
          command: |
            set -x
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker pull scalableminds/fossildb:${CIRCLE_BRANCH}__${COMMON_BUILD_NUM}
            docker pull scalableminds/fossildb-client:${CIRCLE_BRANCH}__${COMMON_BUILD_NUM}
            docker logout
      - run:
          name: Start fossildb
          command: >
            FOSSILDB_TAG=${CIRCLE_BRANCH}__${COMMON_BUILD_NUM}
            docker-compose up -d fossildb
      - run:
          name: Wait a second
          command: sleep 1
      - run:
          name: Check health endpoint
          command: >
            FOSSILDB_CLIENT_TAG=${CIRCLE_BRANCH}__${COMMON_BUILD_NUM}
            docker-compose run fossildb-health-check

workflows:
  version: 2
  default:
    jobs:
      - set_common_build_number
      - build_and_push_db:
          requires:
            - set_common_build_number
      - build_and_push_client:
          requires:
            - set_common_build_number
      - smoketest:
          requires:
            - set_common_build_number
            - build_and_push_db
            - build_and_push_client
