version: 2
jobs:
  build_and_push_db:
    machine:
      image: circleci/classic:latest
    environment:
      SBT_VERSION_TAG: sbt-0.13.15_mongo-3.2.17_node-8.x_jdk-8
      USER_UID: 1001
      USER_GID: 1001
    steps:
      - checkout
      - run:
          name: Prepare dependency folders
          command: mkdir -p ~/.m2 ~/.ivy2 ~/.sbt
      - restore_cache:
          key: cache-{{ .Branch }}
      - run:
          name: Build server
          command: docker-compose run sbt sbt assembly
      - save_cache:
          key: cache-{{ .Branch }}
          paths:
            - "~/.m2"
            - "~/.ivy2"
            - "~/.sbt"
      - run:
          name: Build server docker image
          command: |
            docker build \
            -t scalableminds/fossildb:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} \
            -t scalableminds/fossildb:${CIRCLE_BRANCH} \
            .
      - run:
          name: Push to DockerHub
          command: |
            set -x
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push scalableminds/fossildb:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM}
            docker push scalableminds/fossildb:${CIRCLE_BRANCH}
            docker logout
  build_and_push_client:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Build client docker image
          command: |
            docker build \
            -f client/Dockerfile \
            -t scalableminds/fossildb-client:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} \
            -t scalableminds/fossildb-client:${CIRCLE_BRANCH} \
            .
      - run:
          name: Push to DockerHub
          command: |
            set -x
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push scalableminds/fossildb-client:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM}
            docker push scalableminds/fossildb-client:${CIRCLE_BRANCH}
            docker logout

workflows:
  version: 2
  default:
    jobs:
      - build_and_push_db
      - build_and_push_client
