version: 2
jobs:
  build_and_push:
    machine:
      image: circleci/classic:latest
    environment:
      SBT_VERSION_TAG: sbt-0.13.15_mongo-3.2.17_node-8.x_jdk-8
      USER_UID: 1001
      USER_GID: 1001
      TARGET_DIR: &target_dir target/scala-2.12
    steps:
      - checkout
      - run:
          name: Prepare dependency folders
          command: mkdir -p ~/.m2 ~/.ivy2 ~/.sbt
      - restore_cache:
          key: cache-{{ .Branch }}
      - run:
          name: Build server
          command: docker-compose run -e CI=$CI sbt sbt assembly
      - run:
          name: Get FossilDB version
          command: docker-compose run sbt java -jar $TARGET_DIR/fossildb.jar --version > $TARGET_DIR/version
      - save_cache:
          key: cache-{{ .Branch }}
          paths:
            - "~/.m2"
            - "~/.ivy2"
            - "~/.sbt"
      - run:
          name: Build server docker image
          command: |
            docker build \
            -t scalableminds/fossildb:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} \
            -t scalableminds/fossildb:${CIRCLE_BRANCH} \
            .

      - run:
          name: Smoketest
          command: >
            FOSSILDB_TAG=${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM}
            docker-compose up -d fossildb
            sleep 1
            FOSSILDB_CLIENT_TAG=${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM}
            docker-compose run fossildb-health-check
            docker-compose down

      - run:
          name: Build client docker image
          command: |
            docker build \
            -f client/Dockerfile \
            -t scalableminds/fossildb-client:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} \
            -t scalableminds/fossildb-client:${CIRCLE_BRANCH} \
            .
      - run:
          name: Push to DockerHub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push scalableminds/fossildb:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM}
            docker push scalableminds/fossildb:${CIRCLE_BRANCH}
            docker push scalableminds/fossildb-client:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM}
            docker push scalableminds/fossildb-client:${CIRCLE_BRANCH}
            docker logout

      - run:
          name: Install ghr
          command: >
            sudo add-apt-repository ppa:gophers/archive
            sudo apt-get update
            sudo apt-get install golang-1.10-go
            go get github.com/tcnksm/ghr
      - run:
          name: Install git-semver
          command: |
            set -x
            git clone https://github.com/markchalloner/git-semver.git
            cd git-semver
            git checkout 2.0.2
            ./install.sh
      - run:
          name: Show version
          command: cat version
      - run:
          name: Release jar on Github
          command: >
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ghr
              -t $GITHUB_TOKEN
              -u scalableminds
              -r fossildb
              -c $(git rev-parse HEAD)
              -b "executable jar of __FossilDB__"
              $(cat version | tr -d [:space:])
              fossildb.jar
            fi

workflows:
  version: 2
  default:
    jobs:
      - build_and_push
