version: 2
jobs:
  build_and_push:
    machine:
      image: ubuntu-2004:202111-02
    environment:
      SBT_VERSION_TAG: master__6455790032
      USER_UID: 1000
      USER_GID: 1000
      TARGET_DIR: target/scala-2.13
    steps:
      - checkout

      - run:
          name: Prepare dependency folders
          command: mkdir -p ~/.m2 ~/.ivy2 ~/.sbt

      - restore_cache:
          key: cache-{{ .Branch }}

      - run:
         name: debug git output
         command: docker-compose run -T -e CI=$CI sbt bash -c "git config --global --add safe.directory /fossildb && sbt assembly"

      - run:
          name: Build server
          command: docker-compose run -T -e CI=$CI sbt bash -c "git config --global --add safe.directory /fossildb && sbt assembly"

      - run:
          name: Get FossilDB version
          command: docker-compose run -T sbt java -jar $TARGET_DIR/fossildb.jar --version > $TARGET_DIR/version

      - save_cache:
          key: cache-{{ .Branch }}
          paths:
            - "~/.m2"
            - "~/.ivy2"
            - "~/.sbt"

      - run:
          name: Build server docker image
          command: |
            docker build \
            -t scalableminds/fossildb:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} \
            -t scalableminds/fossildb:${CIRCLE_BRANCH} \
            .
      - run:
          name: Build client docker image
          command: |
            docker build \
            -f client/Dockerfile \
            -t scalableminds/fossildb-client:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} \
            -t scalableminds/fossildb-client:${CIRCLE_BRANCH} \
            .

      - run:
          name: Smoke test
          command: |
            FOSSILDB_TAG=${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} \
            docker-compose up -d fossildb
            sleep 1
            FOSSILDB_TAG=${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} \
            FOSSILDB_CLIENT_TAG=${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} \
            docker-compose run fossildb-health-check
            docker-compose down

      - run:
          name: Push to Dockerhub
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push scalableminds/fossildb:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM}
            docker push scalableminds/fossildb:${CIRCLE_BRANCH}
            docker push scalableminds/fossildb-client:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM}
            docker push scalableminds/fossildb-client:${CIRCLE_BRANCH}
            docker logout

      - run:
          name: Show version
          command: cat $TARGET_DIR/version

      - run:
          name: Release JAR on Github
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                wget https://github.com/cli/cli/releases/download/v2.18.1/gh_2.18.1_linux_amd64.deb
                sudo apt install ./gh_2.18.1_linux_amd64.deb
                TAG_NAME="$(cat $TARGET_DIR/version | tr -d [:space:])"
                gh release create $TAG_NAME -t "$TAG_NAME $(git log -1 --pretty=%B)" -R scalableminds/fossildb --target $(git rev-parse HEAD) -n "Executable JAR of __FossilDB__" $TARGET_DIR/fossildb.jar
            fi

workflows:
  version: 2
  circleci_build:
    jobs:
      - build_and_push:
          context:
            - DockerHub
