version: 2
jobs:
  build_and_push:
    machine:
      image: circleci/classic:latest
    environment:
      SBT_VERSION_TAG: sbt-0.13.15_mongo-3.2.17_node-8.x_jdk-8
      USER_UID: 1001
      USER_GID: 1001
      TARGET_DIR: target/scala-2.12
    steps:
      - checkout
      - run:
          name: Prepare dependency folders
          command: mkdir -p ~/.m2 ~/.ivy2 ~/.sbt

      - restore_cache:
          key: cache-{{ .Branch }}
      - run:
          name: Build server
          command: docker-compose run -e CI=$CI sbt sbt assembly
      - run:
          name: Get FossilDB version
          command: docker-compose run sbt java -jar $TARGET_DIR/fossildb.jar --version > $TARGET_DIR/version
      - save_cache:
          key: cache-{{ .Branch }}
          paths:
            - "~/.m2"
            - "~/.ivy2"
            - "~/.sbt"

      - run:
          name: Build server docker image
          command: |
            docker build \
            -t scalableminds/fossildb:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} \
            -t scalableminds/fossildb:${CIRCLE_BRANCH} \
            .
      - run:
          name: Build client docker image
          command: |
            docker build \
            -f client/Dockerfile \
            -t scalableminds/fossildb-client:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} \
            -t scalableminds/fossildb-client:${CIRCLE_BRANCH} \
            .

      - run:
          name: Smoke test
          command: |
            set -x
            echo ${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM}
            FOSSILDB_TAG=${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} \
            docker-compose up -d fossildb
            sleep 1
            FOSSILDB_CLIENT_TAG=${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} \
            docker-compose run fossildb-health-check
            docker-compose down

      - run:
          name: Push to Dockerhub
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push scalableminds/fossildb:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM}
            docker push scalableminds/fossildb:${CIRCLE_BRANCH}
            docker push scalableminds/fossildb-client:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM}
            docker push scalableminds/fossildb-client:${CIRCLE_BRANCH}
            docker logout

      - run:
          name: Show version
          command: cat $TARGET_DIR/version
      - run:
          name: Release JAR on Github
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              sudo add-apt-repository ppa:gophers/archive
              sudo apt-get update
              sudo apt-get install -y golang-1.10-go
              go get github.com/tcnksm/ghr

              ghr \
                -t $GITHUB_TOKEN \
                -u scalableminds \
                -r fossildb \
                -c $(git rev-parse HEAD) \
                -b "Executable JAR of __FossilDB__" \
                $(cat $TARGET_DIR/version | tr -d [:space:]) \
                $TARGET_DIR/fossildb.jar
            fi

workflows:
  version: 2
  default:
    jobs:
      - build_and_push
